#!/bin/bash

# System package installation
apt-get update && apt-get install -y sudo

sudo apt-get update && \
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common && \
sudo add-apt-repository -y universe && \
sudo apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools build-essential xvfb freeglut3-dev
sudo apt-get install -y python3 python3-pip python3-numpy python3-pandas python3-skimage python3-munkres
sudo pip3 install --break-system-packages skan torch

ln -s /usr/lib/x86_64-linux-gnu/libglut.so.3.12 /usr/lib/x86_64-linux-gnu/libglut.so.3

# Initialize virtual display for vlab
Xvfb :99 -screen 0 1280x1024x24 &
export DISPLAY=:99
export XDG_RUNTIME_DIR=/tmp/runtime-root

# VLAB Installation following official instructions
echo "=== VLAB Installation Process ==="

# Step 1: Installing the distribution (already done via Dockerfile)
echo "Step 1: Distribution already extracted to /app/vlab-5.0"

# Change to vlab directory for Step 1d
cd /app/vlab-5.0

echo "Step 1d: Running postinstall.sh..."
./bin/postinstall.sh

# Step 2 & 3: Set up VLAB environment directly 
echo "Step 2-3: Setting up VLAB environment for current session..."

# Skip the interactive setup.sh and use the sourceme.sh generated by postinstall.sh
if [ -f "bin/sourceme.sh" ]; then
    echo "Sourcing VLAB environment from: $(pwd)/bin/sourceme.sh"
    source bin/sourceme.sh
    echo "VLAB environment loaded successfully!"
else
    echo "ERROR: bin/sourceme.sh not found. postinstall.sh may have failed."
    return 1
fi

# Initialize VLAB configuration
echo "Initializing VLAB configuration..."
./bin/govlab.sh

# Step 4: Testing the installation
echo "Step 4: Testing VLAB installation..."
echo "VLAB environment variables:"
echo "  VLABROOT: $VLABROOT"
echo "  VLABBIN: $VLABBIN"
echo "  PATH includes VLAB: $(echo $PATH | grep -o '[^:]*vlab[^:]*')"

if command -v vlab-splash >/dev/null 2>&1; then
    echo "✅ VLAB installation successful! vlab-splash command found."
elif command -v browser >/dev/null 2>&1; then
    echo "✅ VLAB tools available! browser command found."
else
    echo "⚠️  VLAB commands not found in PATH."
    echo "Current PATH: $PATH"
    echo "Expected VLABBIN: $VLABBIN"
fi

echo "=== VLAB Installation Complete ==="
echo "You can now run VLAB commands like: browser, lpfg, cpfg, vlab-splash"
