#!/bin/bash

# VLAB Setup Script
# Assumes system dependencies are installed via Dockerfile

# Initialize virtual display for vlab (if not already running)
if ! pgrep Xvfb >/dev/null; then
    echo "Starting Xvfb..."
    # Check if we can write to /tmp/.X11-unix, if not try to use a local one
    Xvfb :99 -screen 0 1280x1024x24 &
    sleep 2 # Give it a moment to start
fi
export DISPLAY=:99
export XDG_RUNTIME_DIR=/tmp/runtime-root

# VLAB Installation following official instructions
echo "=== VLAB Installation Process ==="

# Step 1: Installing the distribution (already done via Dockerfile copy)
echo "Step 1: Distribution should be at /app/vlab"

if [ ! -d "/app/vlab" ]; then
    echo "ERROR: /app/vlab directory not found. Did the Docker COPY fail?"
    return 1
fi

# Change to vlab directory for Step 1d
cd /app/vlab || return

echo "Step 1d: Running postinstall.sh..."
# Check permission/executable
# chmod +x bin/postinstall.sh (Skipped because Dockerfile sets 777)
./bin/postinstall.sh

# Step 2 & 3: Set up VLAB environment directly 
echo "Step 2-3: Setting up VLAB environment for current session..."

# Skip the interactive setup.sh and use the sourceme.sh generated by postinstall.sh
if [ -f "bin/sourceme.sh" ]; then
    echo "Sourcing VLAB environment from: $(pwd)/bin/sourceme.sh"
    source bin/sourceme.sh
    echo "VLAB environment loaded successfully!"
else
    echo "ERROR: bin/sourceme.sh not found. postinstall.sh may have failed."
    return 1
fi

# Initialize VLAB configuration
echo "Initializing VLAB configuration..."
./bin/govlab.sh

# Step 4: Testing the installation
echo "Step 4: Testing VLAB installation..."
echo "VLAB environment variables:"
echo "  VLABROOT: $VLABROOT"
echo "  VLABBIN: $VLABBIN"
echo "  PATH includes VLAB: $(echo $PATH | grep -o '[^:]*vlab[^:]*')"

if command -v vlab-splash >/dev/null 2>&1; then
    echo "VLAB installation successful! vlab-splash command found."
elif command -v browser >/dev/null 2>&1; then
    echo "VLAB tools available! browser command found."
else
    echo "VLAB commands not found in PATH."
    echo "Current PATH: $PATH"
    echo "Expected VLABBIN: $VLABBIN"
fi

echo "=== VLAB Installation Complete ==="
echo "You can now run VLAB commands like: browser, lpfg, cpfg, vlab-splash"

cd /app/vlab/oofs/ext || return