# Comments generated by LLM

# ==============================================================================
# Research Pipeline (Resume-Safe)
# ==============================================================================
# Stages covered:
#   1) Validate/skip completed baseline HP tuning
#   2) Quick convergence testing (reduced matrix)
#   3) Quick final HP tune
#
# This script intentionally stops before final all-plant training/optimization.

set -euo pipefail
umask 000

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ------------------------------------------------------------------------------
# USER CONFIG
# ------------------------------------------------------------------------------

PLANT_NAME="Plant_023-1"
DATASET_SPECS=(
    "1000 200 500"
    "20000 4000 10000"
)

# Set to 1 if you want this script to run full baseline HP tuning when missing.
RUN_BASE_HP_IF_MISSING="${RUN_BASE_HP_IF_MISSING:-0}"

# Convergence (quick matrix)
CONV_FRACTIONS=(0.25 0.5 1.0)
CONV_EPOCH_CONFIGS=(
    "25 5"
    "50 10"
)
CONV_REPLICATES=2

# Best HP seeds from prior tuning
MLP_LR="1e-3"
MLP_BS="1"
SINKHORN_LR="5e-4"
SINKHORN_BS="16"

# Final HP quick tune
FINAL_HP_REPLICATES=2
FINAL_HP_EPOCHS=75
FINAL_HP_PATIENCE=8
FINAL_HP_FRACTION=1.0

# MLP quick local search around current best
FINAL_MLP_LRS=(1e-3 5e-4)
FINAL_MLP_BS=(1 4 8)

# Sinkhorn quick local search around current best
FINAL_SINKHORN_LRS=(5e-4 1e-3)
FINAL_SINKHORN_BS=(8 16 32)

# Shared optimizer settings
OPT_RESTARTS=3
OPT_STEPS=250

# Paths
PIPELINE_ROOT="Research Pipeline"
STATE_DIR="${PIPELINE_ROOT}/.state"
LOG_FILE="${PIPELINE_ROOT}/pipeline.log"
QUICK_CONV_DIR="Convergence Tests/Convergence_Quick_${PLANT_NAME}"
FINAL_HP_ROOT="Final HP Tune/${PLANT_NAME}"

mkdir -m 777 -p "$PIPELINE_ROOT" "$STATE_DIR" "$FINAL_HP_ROOT" "$QUICK_CONV_DIR"

# ------------------------------------------------------------------------------
# HELPERS
# ------------------------------------------------------------------------------

log() {
    local msg="$1"
    echo "[$(date +"%Y-%m-%d %H:%M:%S")] $msg" | tee -a "$LOG_FILE"
}

mark_stage() {
    local stage="$1"
    local marker="${STATE_DIR}/${stage}.done"
    date +"%Y-%m-%d %H:%M:%S" > "$marker"
}

stage_done() {
    local stage="$1"
    [[ -f "${STATE_DIR}/${stage}.done" ]]
}

dataset_complete() {
    local d="$1"
    [[ -f "${d}/Train.csv" && -f "${d}/Validation.csv" && -f "${d}/Test.csv" ]]
}

ensure_dataset_in_main_store() {
    local plant="$1"
    local train_size="$2"
    local val_size="$3"
    local test_size="$4"

    local dataset_name="${plant}-${train_size}_${val_size}_${test_size}"
    local main_dir="Datasets/${dataset_name}"
    local alt_dir="Convergence Tests/Datasets/${dataset_name}"

    if dataset_complete "$main_dir"; then
        log "Dataset ready in main store: $main_dir"
        return 0
    fi

    if dataset_complete "$alt_dir"; then
        log "Copying precomputed dataset from alternate store: $alt_dir -> $main_dir"
        mkdir -m 777 -p "$main_dir"
        cp -a "${alt_dir}/." "$main_dir/"
        return 0
    fi

    log "Generating missing dataset: $dataset_name"
    mkdir -m 777 -p "$main_dir"
    python3 generate_dataset.py \
        --plant "$plant" \
        --train_size "$train_size" \
        --val_size "$val_size" \
        --test_size "$test_size" \
        --output_dir "$main_dir"
}

# ------------------------------------------------------------------------------
# STAGE 0: DATASET PREP (REUSE FIRST)
# ------------------------------------------------------------------------------

log "========== STAGE 0: Dataset Prep =========="
for spec in "${DATASET_SPECS[@]}"; do
    read -r train_size val_size test_size <<< "$spec"
    ensure_dataset_in_main_store "$PLANT_NAME" "$train_size" "$val_size" "$test_size"
done
mark_stage "stage0_datasets"

# ------------------------------------------------------------------------------
# STAGE 1: BASELINE HP TUNING CHECK (COMPLETED STAGE)
# ------------------------------------------------------------------------------

log "========== STAGE 1: Baseline HP Tuning Check =========="
base_hp_found=1
for spec in "${DATASET_SPECS[@]}"; do
    read -r train_size val_size test_size <<< "$spec"
    dataset_name="${PLANT_NAME}-${train_size}_${val_size}_${test_size}"

    if ! find "Hyperparameter Tuning" -maxdepth 2 -type f -name "tuning_summary.csv" 2>/dev/null | grep -q "$dataset_name"; then
        base_hp_found=0
        log "Baseline HP results not found for dataset: $dataset_name"
    else
        log "Baseline HP results found for dataset: $dataset_name"
    fi
done

if [[ "$base_hp_found" -eq 1 ]]; then
    log "Baseline HP stage already complete. Skipping rerun."
elif [[ "$RUN_BASE_HP_IF_MISSING" == "1" ]]; then
    log "Running full baseline HP tuning because RUN_BASE_HP_IF_MISSING=1"
    bash ./run_hp_tuning.sh
else
    log "Skipping baseline HP rerun (set RUN_BASE_HP_IF_MISSING=1 to force)."
fi
mark_stage "stage1_base_hp_check"

# ------------------------------------------------------------------------------
# STAGE 2: QUICK CONVERGENCE (RESUME SAFE)
# ------------------------------------------------------------------------------

log "========== STAGE 2: Quick Convergence =========="

# Convergence uses large dataset only (same as current setup)
CONV_DATASET_NAME="${PLANT_NAME}-20000_4000_10000"

for frac in "${CONV_FRACTIONS[@]}"; do
    for cfg in "${CONV_EPOCH_CONFIGS[@]}"; do
        read -r max_epochs patience <<< "$cfg"

        log "Convergence config: frac=${frac}, epochs=${max_epochs}, patience=${patience}"

        python3 tune_models.py \
            --dataset "$CONV_DATASET_NAME" \
            --plant "$PLANT_NAME" \
            --models mlp \
            --learning-rates "$MLP_LR" \
            --batch-sizes "$MLP_BS" \
            --replicates "$CONV_REPLICATES" \
            --dataset-fraction "$frac" \
            --epochs "$max_epochs" \
            --patience "$patience" \
            --opt-restarts "$OPT_RESTARTS" \
            --opt-steps "$OPT_STEPS" \
            --tuning-dir "$QUICK_CONV_DIR" \
            --resume

        python3 tune_models.py \
            --dataset "$CONV_DATASET_NAME" \
            --plant "$PLANT_NAME" \
            --models sinkhorn \
            --learning-rates "$SINKHORN_LR" \
            --batch-sizes "$SINKHORN_BS" \
            --replicates "$CONV_REPLICATES" \
            --dataset-fraction "$frac" \
            --epochs "$max_epochs" \
            --patience "$patience" \
            --opt-restarts "$OPT_RESTARTS" \
            --opt-steps "$OPT_STEPS" \
            --tuning-dir "$QUICK_CONV_DIR" \
            --resume
    done
done

python3 convergence_test.py \
    --summary-file "${QUICK_CONV_DIR}/convergence_summary.txt" \
    --tuning-dir "$QUICK_CONV_DIR"

mark_stage "stage2_quick_convergence"

# ------------------------------------------------------------------------------
# STAGE 3: QUICK FINAL HP TUNE (RESUME SAFE)
# ------------------------------------------------------------------------------

log "========== STAGE 3: Quick Final HP Tune =========="

for spec in "${DATASET_SPECS[@]}"; do
    read -r train_size val_size test_size <<< "$spec"
    dataset_name="${PLANT_NAME}-${train_size}_${val_size}_${test_size}"
    stage_dir="${FINAL_HP_ROOT}/${dataset_name}"

    mkdir -m 777 -p "$stage_dir"
    log "Final HP quick tune dataset: $dataset_name"

    python3 tune_models.py \
        --dataset "$dataset_name" \
        --plant "$PLANT_NAME" \
        --models mlp \
        --learning-rates "${FINAL_MLP_LRS[@]}" \
        --batch-sizes "${FINAL_MLP_BS[@]}" \
        --replicates "$FINAL_HP_REPLICATES" \
        --dataset-fraction "$FINAL_HP_FRACTION" \
        --epochs "$FINAL_HP_EPOCHS" \
        --patience "$FINAL_HP_PATIENCE" \
        --opt-restarts "$OPT_RESTARTS" \
        --opt-steps "$OPT_STEPS" \
        --tuning-dir "$stage_dir" \
        --resume

    python3 tune_models.py \
        --dataset "$dataset_name" \
        --plant "$PLANT_NAME" \
        --models sinkhorn \
        --learning-rates "${FINAL_SINKHORN_LRS[@]}" \
        --batch-sizes "${FINAL_SINKHORN_BS[@]}" \
        --replicates "$FINAL_HP_REPLICATES" \
        --dataset-fraction "$FINAL_HP_FRACTION" \
        --epochs "$FINAL_HP_EPOCHS" \
        --patience "$FINAL_HP_PATIENCE" \
        --opt-restarts "$OPT_RESTARTS" \
        --opt-steps "$OPT_STEPS" \
        --tuning-dir "$stage_dir" \
        --resume

    python3 convergence_test.py \
        --summary-file "${stage_dir}/final_hp_summary.txt" \
        --tuning-dir "$stage_dir"
done

mark_stage "stage3_quick_final_hp"

# ------------------------------------------------------------------------------
# PIPELINE END (INTENTIONAL)
# ------------------------------------------------------------------------------

log "========== PIPELINE COMPLETE (up to final HP tune) =========="
log "Quick convergence outputs: ${QUICK_CONV_DIR}"
log "Quick final HP tune outputs: ${FINAL_HP_ROOT}"
log "Final all-plant training/optimization intentionally not run in this script."
